name: Deploy Azure Functions

on:
  push:
    branches:
      - main

env:
  AZURE_FUNCTIONAPP_NAME: archive-function-app
  AZURE_FUNCTIONAPP_NAME_2: retrieve-function-app
  AZURE_FUNCTIONAPP_PACKAGE_PATH_1: './archive_old_records'
  AZURE_FUNCTIONAPP_PACKAGE_PATH_2: './retrieve_billing_record'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Setup Azure Functions Core Tools
        uses: Azure/setup-azure-functions@v1
        with:
          version: '4'

      - name: Archive Function - Deploy to Azure
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH_1 }}
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

      - name: Retrieve Function - Deploy to Azure
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME_2 }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH_2 }}
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE_2 }}
